package io.github.untoastedtoast.foldio.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme
val primaryLight = Color(0xFF1A6B7A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB6ECFA)
val onPrimaryContainerLight = Color(0xFF002025)

val secondaryLight = Color(0xFF4A6374)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCDE7F5)
val onSecondaryContainerLight = Color(0xFF051E2B)

val tertiaryLight = Color(0xFF5C5E9D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFE1E0FF)
val onTertiaryContainerLight = Color(0xFF181A55)

val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)

val backgroundLight = Color(0xFFF5FAFB)
val onBackgroundLight = Color(0xFF171C1E)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171C1E)
val surfaceVariantLight = Color(0xFFDBE4E8)
val onSurfaceVariantLight = Color(0xFF3F484C)
val outlineLight = Color(0xFF6F797C)
val outlineVariantLight = Color(0xFFBFC8CC)
val surfaceContainerLight = Color(0xFFE8F3F5)
val surfaceContainerHighLight = Color(0xFFDCEDF0)
val surfaceContainerLowestLight = Color(0xFFF0F8FA)
val surfaceContainerLowLight = Color(0xFFEBF4F6)
val surfaceContainerHighestLight = Color(0xFFCDDDE0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C3639)
val inverseOnSurfaceLight = Color(0xFFEEF3F5)
val inversePrimaryLight = Color(0xFF82D3E3)

// Dark theme
val primaryDark = Color(0xFF82D3E3)
val onPrimaryDark = Color(0xFF00363E)
val primaryContainerDark = Color(0xFF004F5A)
val onPrimaryContainerDark = Color(0xFFB6ECFA)

val secondaryDark = Color(0xFFB2CBD9)
val onSecondaryDark = Color(0xFF1D3441)
val secondaryContainerDark = Color(0xFF344A57)
val onSecondaryContainerDark = Color(0xFFCDE7F5)

val tertiaryDark = Color(0xFFC2C3F3)
val onTertiaryDark = Color(0xFF2B2D60)
val tertiaryContainerDark = Color(0xFF434476)
val onTertiaryContainerDark = Color(0xFFE1E0FF)

val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)

val backgroundDark = Color(0xFF0F1417)
val onBackgroundDark = Color(0xFFDEE3E6)
val surfaceDark = Color(0xFF0F1417)
val onSurfaceDark = Color(0xFFDEE3E6)
val surfaceVariantDark = Color(0xFF3F484C)
val onSurfaceVariantDark = Color(0xFFBFC8CC)
val outlineDark = Color(0xFF899296)
val outlineVariantDark = Color(0xFF3F484C)
val surfaceContainerDark = Color(0xFF1B2427)
val surfaceContainerHighDark = Color(0xFF252F32)
val surfaceContainerLowestDark = Color(0xFF0A1013)
val surfaceContainerLowDark = Color(0xFF171C1E)
val surfaceContainerHighestDark = Color(0xFF303A3D)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E6)
val inverseOnSurfaceDark = Color(0xFF2C3639)
val inversePrimaryDark = Color(0xFF1A6B7A)
